### ISSUE TITLE
cropping images too early

### ISSUE THREAD

**Issue by obartra** [obartra/reflex#238]
As this error suggests: https://circleci.com/gh/obartra/reflex/1668#tests/containers/1:

```shell
 safari    ✖ Error: There are some read requests waitng on finished stream
 safari       at ReadStream.onend (_stream_readable.js:584:10)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
 safari   FAILED:  1 errors and 13 passed (43.316s)
```

Either sharp is starting to crop before the image is ready (saucelabs issue) or it reports it's done cropping when it's still using it (sharp issue). It's probably the later but we should investigate

**Comment by obartra** [comment]
I haven't seen this issue since [this](https://github.com/obartra/reflex/pull/241/files#diff-2c29da9c51430f860f51bf746942e29fR28) change but I'll keep the ticket open a bit longer just to make sure
